### ISSUE TITLE
Create Releases

### ISSUE THREAD

**Issue by ainola** [EliverLara/Ant#10]
For packaging, it would be handy to have releases.

Thanks!

**Comment by PSSGCSim** [comment]
Yes, but I would suggest you use iteration number of commit followed by it's short hash. As it is independent of the release number/tag.
Take this as an alternative and not as a guidline.

Example:
`echo v$(git rev-list HEAD | wc -l).$(git rev-parse --short HEAD)`

Produces:
`v11.18301f9`

More examples can be found at https://stackoverflow.com/questions/4120001/what-is-the-git-equivalent-for-revision-number

**Comment by androidnisse** [comment]
Yes please. The releases on Gnome-look does not have the release number in their name.
