### ISSUE TITLE
Switch nobs are strange ellipses

### ISSUE THREAD

**Issue by keeferrourke** [EliverLara/Ant#11]
See screenshot below. The switch nobs look really odd, since they aren't circular. Correct this by making the border radius for the nob 100%. This issue is also present in the Ant-bloody and Ant-Dracula variants.

Below is a screenshot of Gnome Tweak Tool under Gnome 3.24.x on Fedora 26, after a fresh installation and download of Ant from gnome-look.org. 

![screenshot from 2017-09-26 15-18-25](https://user-images.githubusercontent.com/6888381/30879676-0e1ad818-a2ce-11e7-95be-c043cb20449c.png)

**Comment by EliverLara** [comment]
Thanks @keeferrourke, that's fixed.
