### ISSUE TITLE
Ant-Dracula 1.0 issues on Solus Budgie

### ISSUE THREAD

**Issue by androidnisse** [EliverLara/Ant#15]
Just updated to 1.0 from 0.8 and I got some issues on Solus Budgie.

First the menu looks weird and compact. Don't think it looked like this before.
https://i.imgur.com/YX2B6HV.png

Minimise, maximise and close don't show up until you hover over them. Where it says on and off where coloured buttons before.
https://i.imgur.com/L5zjpzF.png

The three buttons in the bottom of the raven panel where big and coloured before and they are not now.
https://i.imgur.com/4fjMawE.png

These are the things I can see right now. Hope that you can fix them!

**Comment by EliverLara** [comment]
HI, in v1.0 I just added the gnome shell theme, anyway I tested it on solus with budgie desktop and everything seems fine:

![img1](https://user-images.githubusercontent.com/9838260/31557813-f8cb1118-b00f-11e7-8f5d-988626be3ea7.png)
![img2](https://user-images.githubusercontent.com/9838260/31557829-044eca8e-b010-11e7-9c53-2226d94db2ee.png)

So if you could provide more information about your OS would be great.

**Comment by PSSGCSim** [comment]
I would suggest running any GUI application from terminal. In GNOME it yields errors if you are missing dependencies to the theme and such. Maybe yours will too.

**Comment by EliverLara** [comment]
Thanks @PSSGCSim , actually that's what i do.

**Comment by androidnisse** [comment]
I just removed the theme downloaded it again and put it in /usr/share/themes and it just works. Sorry for not checking that first, must have been corrupt or something. Thanks for the awesome theme!
