### ISSUE TITLE
Theme not applied to top and side menu

### ISSUE THREAD

**Issue by leunammejii** [EliverLara/Ant#18]
The top and side menus still have the built-in Gnome theme applied.

![screenshot from 2017-10-14 14-16-00](https://user-images.githubusercontent.com/12433311/31579788-e7115a0c-b10b-11e7-8480-d324594ec802.png)

**Comment by EliverLara** [comment]
You must change the shell theme in order to the built-in theme take effect.

**Comment by leunammejii** [comment]
That worked. This is officially vicious! 5 stars!!!
