### ISSUE TITLE
How to select the Dracula version ?

### ISSUE THREAD

**Issue by dinojr** [EliverLara/Ant#19]
I'm cloning this git repo but it seems to only offer the default Ant themes. I have to download the packages from gnome-look to get the Dracula version. Is it possible to choose the Dracula version from this repo ?

**Comment by EliverLara** [comment]
Sorry for now Ant-Dracula and Ant-Bloody variants are only available in gnome-look but I will add them to this repos or maybe I will create a separate repository for each one, I am deciding that.

**Comment by dinojr** [comment]
Ok, thanks.
