### ISSUE TITLE
Maybe use white panel bar on shell theme?

### ISSUE THREAD

**Issue by devillove084** [EliverLara/Ant#20]
I suggest your ant (NotDracula& Not Bloody) shell theme, maybe can use white panel on gnome-shell.css file. I tried change it, but it is waste time. So, I write this issuse for your team. Wish can change is in Ant shell theme. Thank you very much

**Comment by PSSGCSim** [comment]
Are we talking about the black bar when any window is touching the top bar right?

**Comment by EliverLara** [comment]
@PSSGCSim  the top bar now stays white even with maximized windows.

**Comment by PSSGCSim** [comment]
Works like a charm, thank you @EliverLara
