### ISSUE TITLE
Title bar issue

### ISSUE THREAD

**Issue by ThePoPZeRo** [EliverLara/Ant#21]
First thank you for this awesome theme 
but the Titlebar on some apps doesen't transform to dark when I turn on " Global Dark theme "
like the this image for now it seems to be just vlc and firefox and Telegram
![image](https://user-images.githubusercontent.com/18691608/31828811-b05aa87e-b5bb-11e7-9191-8df93cc9b84c.png)
but for vlc I have different problem I'm really don't understand why but when I choose any white theme it look's like the this 
![image](https://user-images.githubusercontent.com/18691608/31829155-c02eef70-b5bc-11e7-859d-61601efc8da6.png)
" Global Dark Theme " doesn't matter if on or off for vlc 
I'm using Manjaro with gnome 3.26
again thanks for your AWESOME THEME

**Comment by EliverLara** [comment]
When you enable the global dark theme some applications must be restarted or even take effect until the next logon, Did you try that?

**Comment by ThePoPZeRo** [comment]
yes I have restarted firefox , telegram , vlc and nothing happened I even re login and restart GDM but again nothing happens 😢

**Comment by ThePoPZeRo** [comment]
I'm sorry I didn't noticed Ant-Dracula version of the theme it fixed the problem with the topbar

but as you can see in the image for vlc there is some places doesn't care about the theme or if global dark theme on or off it's just black but at least it's readable and not looks so bad with united and adwaita dark arc dark

this is image with united theme
![image](https://user-images.githubusercontent.com/18691608/31847267-395a5252-b619-11e7-91ef-12a92dd26ac7.png)

**Comment by ThePoPZeRo** [comment]
I made it readable from qtconfig-qt4
![image](https://user-images.githubusercontent.com/18691608/31847681-41f5f37e-b620-11e7-87bc-88f24669e1d9.png)
I chosed adwaita-qt dark and change background color and button color to make some close look 
but it's not close enough 😞 
any way I found new app 
![image](https://user-images.githubusercontent.com/18691608/31847748-8dd2f066-b621-11e7-813b-446e12e4609b.png)
Gpick the text is white on white background I can't see and it's not a qt based

**Comment by EliverLara** [comment]
That looks so bad, anyway thanks for providing all this information, I'll work on that.

**Comment by ThePoPZeRo** [comment]
I'm did it don't know what was the problem exactly but when I added new user it works fine 
![image](https://user-images.githubusercontent.com/18691608/31863015-e8510aec-b747-11e7-82c5-305991d8f924.png)
but still there is some apps in white and nothing happen when I turn global dark theme on or off
I'm using Ant-Dracula

**Comment by EliverLara** [comment]
That's because those applications use gtk2 and the built-in gtk2 theme doesn't use the dracula colors yet, but it will, thanks for updating the information.

**Comment by ThePoPZeRo** [comment]
oh okay I will wait 😍

**Comment by EliverLara** [comment]
The gtk2 theme is now available in the  [latest version](https://www.gnome-look.org/p/1099856/) :tada:
