### ISSUE TITLE
Add the name of the icon theme used on the figure in README file

### ISSUE THREAD

**Issue by dmitry-kabanov** [EliverLara/Ant#23]
Not really an issue but anyway :-)

I'd like to know the name of the icon theme used in the demo figure shown on the repository's front page.
Is it possible to add this information to the README file?

Thanks!

**Comment by EliverLara** [comment]
You're right, anyway icon theme is [Boston](https://www.gnome-look.org/p/1012402/), i'll add this to readme, Thanks.

**Comment by dmitry-kabanov** [comment]
OK, thanks.
