### ISSUE TITLE
blurry icons in system tray

### ISSUE THREAD

**Issue by bl4ck5un** [EliverLara/Ant#26]
After upgrading to Ubuntu 17.10, which comes with GNOME Shell 3.26.1, the notification icons (sounds, Wi-Fi, etc) in the top bar become blurry unless one hovers the mouse pointer over them. (Only if no application is open. If any window is open, the issue goes away.)

blurry icons if mouse doesn't hover:
![screenshot from 2017-11-05 23-27-47](https://user-images.githubusercontent.com/2434648/32425420-05064334-c281-11e7-901e-928b7f08dce9.png)

clear icons while mouse hovers:
![screenshot from 2017-11-05 23-32-01](https://user-images.githubusercontent.com/2434648/32425553-e0f8bd2c-c281-11e7-8d7e-5bd4f1c41b01.png)

**Comment by aajjbb** [comment]
I can confirm this bug in Gnome 3.26.2 too.

**Comment by spd00** [comment]
Blurry Texts in The bar.. Gnome 3.28.0
![ant](https://user-images.githubusercontent.com/34832784/38164870-e085aad0-352c-11e8-8930-3c3f8180826c.png)
