### ISSUE TITLE
Change the pink color of Dracula

### ISSUE THREAD

**Issue by VladimirDev93** [EliverLara/Ant#27]
How do I change the pink color on Dracula? What is the `CSS` file for it? I've tried to change the color in couple of your `CSS` files but with no luck. I've even recolored the images in `Buttons` folder, still no luck.

Btw, nice theme, it's just I don't like the pink color.

**Comment by EliverLara** [comment]
Hi, which gtk version you use?

For gtk 3.20+ :
* Change the `$selected_bg_color` variable in the `_colors.scss` file (under Ant/gtk-3.20/), 
* Recompile the `gtk.scss` file to generate the corresponding css
* Reload the theme.

For gtk < 3.20 : 
* Change the `selected_bg_color` variable in the `gtk.css` file (under Ant/gtk-3.0/) 
* Reload the theme.

 **Note**
 To recompile  `gtk.scss` just type in your terminal (you must have [sass](http://sass-lang.com/install) installed ): 
`sass gtk.scss gtk.css`

**Comment by VladimirDev93** [comment]
@EliverLara Ok, thank you.

**Comment by d6thsense** [comment]
Hi,
I've been trying to compile the scss file but i'm getting the error:
```
Error: compound selectors may longer be extended.
Consider `@extend %selected_items, :disabled` instead.
See http://bit.ly/ExtendCompound for details.

    selection { @extend %selected_items:disabled; }
                                       ^
  widgets/_base-states.scss 125:40  @import
  _widgets.scss 7:9                 @import
  gtk.scss 9:9                      root stylesheet

```
I'm using SASS version available here: [Dart-Sass 1.5.1](https://github.com/sass/dart-sass/releases/tag/1.5.1)

**Comment by emanjavacas** [comment]
Hey, I've successfully changed the pink color to something else. But still the background color of the icons in the pop up app menu is pink (the one that pops up on Alt+tab). Do you know what could I do to change it? thanks for the awesome theme btw!

**Comment by emanjavacas** [comment]
Nevermind, I found it. It's inside `gnome-shell/_colors.scss` selected_bg_color.

**Comment by nicolasshu** [comment]
Thanks @EliverLara and @anti-mony 
Unfortunately, as of 3/11/2019, one gets the error below if you install sass using NPM 

```
Error: compound selectors may no longer be extended.
Consider `@extend %selected_items, :disabled` instead.
See http://bit.ly/ExtendCompound for details.

    ╷
125 │     selection { @extend %selected_items:disabled; }
    │                         ^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  widgets/_base-states.scss 125:25  root stylesheet
```

And if you try to install Ruby's sass, then you'll realize that it is no longer supported. You can, however install `node-sass` with the command below

```
npm install -g node-sass
```

and then compile your code with the compilation will work =]

```
$ node-sass gtk.scss gtk.css
```

**Comment by diayush** [comment]
@emanjavacas Hey mate, it's not working for me, could you do me a favor and upload your modified ant theme onto your github, so I could download it? That would be a huge help!

**Comment by Fr3d0509** [comment]
@EliverLara i kow that it looks quite simple, and i assurde you i did everything you wrote, but that doesn't work, any ideas? It doesn't output errors or anything like that
