### ISSUE TITLE
Need help customizing

### ISSUE THREAD

**Issue by meetdilip** [EliverLara/Ant#29]
Hi,

I just tried the Ant theme on 16.04 + Unity. Thanks for the awesome work.

I would like to customize it a bit to my liking. in the launcher, the icons are highlighted by a bubble. Is it possible to make them flat ? Some colour + transparency for highlighting.

I hope you will be able to help me out with this. Thanks for your time.

I solved changing colours using

> For gtk < 3.20 :
> 
>     Change the selected_bg_color variable in the gtk.css file (under Ant/gtk-3.0/)
>     Reload the theme.
>

**Comment by EliverLara** [comment]
Hi, to remove the "bubble" in the launcher icons:
 * Download and extract [this](https://mega.nz/#!BgYCGTYQ!5xi-Lhi43Dki1fWzvwkylihQ7Fj_gYp_uv51yqio9mY) file.
* Copy the contents of the extracted folder in the unity folder under (Ant/unity/) 
* Restart the theme

**Comment by meetdilip** [comment]
Thanks @EliverLara 

Is it possible to remove rounded corners from the breadcrumbs ?

Also, can I make the highlighting at the top like this for breadcrumbs ?

![screenshot-2017-11-23 ubuntu loco council election results](https://user-images.githubusercontent.com/6965443/33159691-99f8b342-d03b-11e7-9a47-7c3f7492a03e.png)

**Comment by EliverLara** [comment]
Yes, for both check out the "csd.css" file under (Ant/gtk-3.0/widgets)

**Comment by meetdilip** [comment]
Thanks. I got the bubbles removed. But there was no highlighting for open apps. Which file defines it ?

**Comment by EliverLara** [comment]
I'm not sure about that, maybe [this](http://www.attabot.org/linux/remove-icon-bubble-background-in-unity-for-sleek-and-flat-look-ubuntu/) could be of more help, , I'm sorry.

**Comment by meetdilip** [comment]
I picked those launcher icons from Adapta. It works fine now. 

I tried adding border-bottom to csd.css . It was not working however. Can you review this code, please ?

```
.titlebar .button,
.titlebar .button:active,
.titlebar .button:checked {
    padding: 5px;
    background-color: transparent;
    border-color: transparent;
    border-bottom: 1px solid #696
    color: @header_fg_color;
    font: bold;
}

.titlebar .button:hover,
.titlebar .button:active:hover,
.titlebar .button:checked,
.titlebar .button:active {
    border-bottom: 1px solid #696
    color: @selected_bg_color;
}

I want to replace the Ant-Red with a border bottom or top of a colour of my choice. Thanks.
```

**Comment by EliverLara** [comment]
I am not able to test the code right now because i'm using gtk3.20, but as a tip if the border property doesn't  work try to use box-shadow to simulate the border, if that does not help, let me know

**Comment by meetdilip** [comment]
@EliverLara Can you tell me how to try border-bottom in gtk 3.2 as well ? I have Sass installed.

How can we check the gtk version ? Thanks.

**Comment by EliverLara** [comment]
For gtk3.20+ check out the "_header-bars.scss" file under (Ant/gtk-3.20/widgets)
