### ISSUE TITLE
xfce4 version possible?

### ISSUE THREAD

**Issue by yuyttenhove** [EliverLara/Ant#30]
Hi, I really love your theme and I have been using it for some time on Gnome now. 
Recently I switched to xfce4 and the gtk-theme works great, however, i do miss the matching decorations for the window borders etc.
Would you be willing to add xfwm4 compatibility?

**Comment by EliverLara** [comment]
Yes, I will start support for xfce soon, or if you want to contribute, PR are always welcome.

**Comment by EliverLara** [comment]
The support for xfce was added!
