### ISSUE TITLE
Ant theme selected items in inactive window

### ISSUE THREAD

**Issue by agraef** [EliverLara/Ant#35]
Here's one Gnome-related issue I just noticed with Ant. Screenies are from gnome-tweak-tool, but it happens with other applications, too. When the window is active, selected items are shown with white text on a pink background:

![screenshot from 2018-01-21 12-30-58](https://user-images.githubusercontent.com/2853977/35193748-9c778ac2-fea7-11e7-877b-6a4c4b7826c9.png)

However, when the mouse hovers over the selected item, then the background color becomes a very light pink so that the item is barely readable:

![screenshot from 2018-01-21 12-36-42](https://user-images.githubusercontent.com/2853977/35193770-f964fea4-fea7-11e7-8252-3436800f5d48.png)

Maybe this is intended. But it becomes even worse when the window is inactive, then the item is just white on a very light gray and thus illegible:

![screenshot from 2018-01-21 12-31-36](https://user-images.githubusercontent.com/2853977/35193776-0fc62330-fea8-11e7-8bf6-5f4d8f2ada8d.png)

**Comment by agraef** [comment]
NB: Same issue with Ant-Bloody and Ant-Nebula (but not with Ant-Dracula).

**Comment by EliverLara** [comment]
Thank you very much for reporting, I had not noticed that, Working on that ...
