### ISSUE TITLE
xfce white pixel in window decorations

### ISSUE THREAD

**Issue by agraef** [EliverLara/Ant#36]
AFAICT, this only affects the variants with dark window decorations (so all of them except Ant proper, the screenshot below is from Ant-Nebula):

![image](https://user-images.githubusercontent.com/2853977/35199455-145558c0-fefe-11e7-9731-c5361777fb14.png)

Note the white pixel in the upper left and upper right corner of the window title bar, this actually comes from the window decoration (it disappears when setting a different window manager theme).

**Comment by EliverLara** [comment]
Hi @agraef thank you again for reporting, that's fixed and available on [gnome-look](https://www.opendesktop.org/p/1099856/)!

**Comment by agraef** [comment]
Nice, thanks a bunch!
