### ISSUE TITLE
On/off buttons not really "on focus" on Ant Dracula

### ISSUE THREAD

**Issue by morisrc** [EliverLara/Ant#38]
When the button is on seems not on focus, or on low quality. This only affect Ant Dracula (I use no mac style buttons)
![schermata da 2018-01-25 13-05-46](https://user-images.githubusercontent.com/20545323/35387582-9a6b467a-01d0-11e8-9fcd-01b7fff356e5.png)

**Comment by EliverLara** [comment]
Hi. what do you mean "seems not on focus", I see it green when it's activated.

**Comment by morisrc** [comment]
Hi. I mean they seem in a lower quality than the other versions of Ant, like this:
![schermata da 2018-01-26 13-11-27](https://user-images.githubusercontent.com/20545323/35439365-b7bcb6c6-029a-11e8-9955-70e074bf569a.png)
The edges of the buttons are like blurred. 
Maybe it's me, but they seem quite different. I thought it was some bug.

**Comment by EliverLara** [comment]
Thanks for the info, I changed the color of the edge to the switch buttons, now it looks better.
