### ISSUE TITLE
Different shadows depth between gtk2 and gtk3 apps

### ISSUE THREAD

**Issue by yuune** [EliverLara/Ant#39]
Is that possible to fix that without extension or changing mutter's source code ?
![alt-text](https://i.imgur.com/NffJFdr.png)

**Comment by EliverLara** [comment]
Hi, I think it is possible, but I'm not so sure, since it's the wm that currently draws those shadows, maybe I could try to find a balance between the gtk3 and gtk2 shadows, but that would imply increasing the size of gtk3 shadows  and I think for now they are fine.
