### ISSUE TITLE
Gtk2 windows has too big borders for resizing

### ISSUE THREAD

**Issue by lssj** [EliverLara/Ant#4]
In ubuntu 17.10 with the newest gnome shell, gtk2 windows has too big borders (for resizing), you can resize window from distant beyond the visual borders. It creates trouble when having multiple windows opened, while you never know which window you will resize, or makes switching focus on windows impossible because there is invisible resizing area.

PS. Sorry if my description isn't clear enough, I have some language and nomenclature issues. 
PS2. Great theme, thanks!

**Comment by EliverLara** [comment]
Fixed :smiley:
