### ISSUE TITLE
4 pixel border around all GTK+ windows in i3-gaps

### ISSUE THREAD

**Issue by Matthewacon** [EliverLara/Ant#42]
![](https://i.imgur.com/lc2m3xC.png)
There is a white 4 pixel border surrounding all GTK+ windows in i3-gaps. OS info:
`Linux KTorch 4.15.7-1-ARCH #1 SMP PREEMPT Wed Feb 28 19:01:57 UTC 2018 x86_64 GNU/Linux
` The application in the screenshot is GNOME nautilus 3.26.2. This happens in all variants of Ant sources from [Open Desktop](https://www.opendesktop.org/c/1464350441) and using the latest commit in master, 3b47021880375d4de1358f151d539464b6e121bf

**Comment by EliverLara** [comment]
Hi, are you sure it's not a problem with your i3 configuration? if it is not maybe [this](https://github.com/i3/i3/issues/1655)  or [this]( https://amp.reddit.com/r/i3wm/comments/3brqfl/i3gaps_gnome_apps_have_huge_borders_any_ideas/) could help

**Comment by Matthewacon** [comment]
I'm fairly certain that is not the issue. I should've clarified and stated earlier that I attempted the fixes recommended in those threads before making the issue. The current contents of `~/.config/gtk-3.0/gtk.css` are: 
```
.window-frame {
 box-shadow: none; 
 margin: 0;
}
```
I should also mention that I am using compton to enable conditional transparency, shadows, transition effects and gaussian blurring. For reference, this is my [i3 configuration](https://pastebin.com/EBUGudP7) and my [compton configuration](https://pastebin.com/2xyykNgs). I haven't tested this theme on a Gnome installation, as I just recently switched from Gnome to i3. However, I also observed the issue on another clean i3 installation and the issue remains even with the gnome-settings-daemon running. If you need any other system specifications for reproducibility please let me know.

**Comment by EliverLara** [comment]
Hi, thanks for the information and sorry for the late response, unfortunately I have never used i3 and I am not familiar with it, i thought those forums threads would help, so for now I have no way to reproduce the issue, maybe I will need some help, if you want to contribute, PR are always welcome.

**Comment by EliverLara** [comment]
Finally fixed!

**Comment by Matthewacon** [comment]
Completely forgot about this issue
Looking at the diff in 3fc9a80f0d4ffe8370792a72f5de4b44d6603fe3, a simple `grep -Rin '4px'` would've revealed the issue back in 2018 :sweat_smile: 
I'll have to give Ant another try :+1:
