### ISSUE TITLE
Calendar Days With Events not showing

### ISSUE THREAD

**Issue by Erdbeergeist** [EliverLara/Ant#46]
In Unity in Ubuntu 16.04 the days with events dont show up in the calendar in the top right panel, one can click them and then they appear but, by default they become invisible.
![photo_2018-04-18_12-04-33](https://user-images.githubusercontent.com/11724220/38925702-b1ae1918-4300-11e8-82ea-177a528b9cc9.jpg)

**Comment by EliverLara** [comment]
Hi, I'm Sorry, I did not have time to review it but this weekend I will do it and hopefully I will solve it soon, thanks for reporting this.
