### ISSUE TITLE
Issues with overlapping window controls on high DPI screens with display scaling > 100%

### ISSUE THREAD

**Issue by owl-93** [EliverLara/Ant#47]
On high dpi screens, when display scaling is set to higher than 100% (125%, 150%, 175%, 200%, etc), the window controls are not displaying correctly. It seems the yellow minimize button overlaps with the green maximize button and creates a 3rd color (teal) button that minimizes the window. See attached screenshots for detail.

Showing the overlapped buttons that result in minimizing window (minimize button likely on top)
![screenshot from 2018-04-24 14-24-31](https://user-images.githubusercontent.com/7411331/39215153-bf985884-47cb-11e8-9224-a273d3b7a0a2.png)

4k screen at 200% scaling (normal use scaling)
![screenshot from 2018-04-24 14-24-09](https://user-images.githubusercontent.com/7411331/39215200-e4549368-47cb-11e8-9ba5-7f5323d8a038.png)

4k screen at 100% scaling (too small for use)
![screenshot from 2018-04-24 14-23-36](https://user-images.githubusercontent.com/7411331/39215215-f001b560-47cb-11e8-80d5-135913dfe668.png)

**Comment by EliverLara** [comment]
HI, I think this is the same as #9 , so I'll close it like a duplicate.
