### ISSUE TITLE
Dash-to-panel gradient when maximizing window

### ISSUE THREAD

**Issue by msolano00** [EliverLara/Ant#48]
First of all, let me thank you for this gorgeous theme, its the most beautiful theme I have ever seen in Linux. The only issue I have found so far is when maximizing a window.

Under normal conditions, this is how the dash-to-panel bar looks:
![screenshot from 2018-05-03 10-41-38](https://user-images.githubusercontent.com/2273023/39590912-73200466-4ebf-11e8-8941-a3b6183853df.png)

But when I maximize any windows this gradient occurs:
![screenshot from 2018-05-03 10-41-55](https://user-images.githubusercontent.com/2273023/39591629-8a714df8-4ec1-11e8-9f4b-35c2ccd1ab38.png)

When maximizing other themes I don't have the same issue:
![screenshot from 2018-05-03 11-04-23](https://user-images.githubusercontent.com/2273023/39591707-c3eb0c68-4ec1-11e8-9ec0-ba88cc184752.png)

OS: Ubuntu 18.04

**Comment by EliverLara** [comment]
Hi, I'm sorry for the late response, I've tested it on fedora with gnome 3.28.1 but the error does not happen, at this moment I have no way to reproduce the issue (since I don't use ubuntu) so let me try to install ubuntu and see what happens.

**Comment by jacobhempel** [comment]
Would just like to add that I also have this issue on Ubuntu 18.04 :)
