### ISSUE TITLE
the filename of files selected in xfce Thunar disappear

### ISSUE THREAD

**Issue by godcrying** [EliverLara/Ant#53]
clicked on a file, I only saw a red square without a filename in it.
I'm using Archlinux.

**Comment by godcrying** [comment]
![image](https://user-images.githubusercontent.com/11704413/43356836-af9178ce-92aa-11e8-987b-f14de94c47f7.png)
just like this picture

**Comment by EliverLara** [comment]
Cool, let me try to reproduce it.
