### ISSUE TITLE
GDM/Login Screen Theme

### ISSUE THREAD

**Issue by faahim** [EliverLara/Ant#54]
Hi!

Thank you so much for the amazing theme! I'm super picky about themes and I fell in love with Ant right after I applied it for the first time. It's amazing! Thanks a ton! :smile: 

I'm just curious whether Ant also has a GDM login screen theme like some other shell them does. The only part in my system that I'm not completely happy with the look of, is my default login screen.

If Ant already has a GDM theme, could you please give me some instruction on how to apply it? I looked inside the theme folder for a `gnome-shell-theme.gresource` file as suggested [here](https://github.com/nana-4/materia-theme/wiki/GDM-Theme) and [here](https://github.com/skatrosh/gdm-arc-theme), but couldn't find it. 

If Ant doesn't have a GDM theme yet, do you have any plan to implement it in the future? In that case, I'd love to help! I don't know much about Linux theming, but I'm interested to learn and my CSS skill is fairly good.

Looking forward to hearing your thoughts! Thanks again! :smiley:

**Comment by EliverLara** [comment]
Hi, I had not planned an implementation of the GDM theme, but if you want to contribute to the implementation it would be great!.

**Comment by JuanCAlpizar** [comment]
@EliverLara is there a place to learn about theming? I'd like the idea about helping on the project cause I quite like it and I'm familiar with CSS myself (which as far as I understand is what is used to theme stuff), but I don't know how GTK theming works, neither for apps or GDM.
