### ISSUE TITLE
Files in file selector disappear Slack

### ISSUE THREAD

**Issue by wbvtler** [EliverLara/Ant#55]
I have reached out to Slack and confirmed together that we were unable to reproduce this in other themes.

![upload_profile_photo](https://user-images.githubusercontent.com/29716496/43284785-867be13c-90e2-11e8-9019-2dcaab826421.png)

An important note: I could still select files, but just couldn't see them.

Also, when I click "cancel", the entire app freezes, even after closing and reopening the window, until I end the process from the system monitor. This does not happen when I use other themes.

I am using Ubuntu 18.04 with the GNOME desktop.

**Comment by EliverLara** [comment]
Hi, thanks for reporting, I tried to reproduce it in fedora 28 with gnome 3.28.2 but everything seems fine (as you can see below) , so let me check it in ubuntu and see what happens.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9838260/43289641-342fcfb0-90f1-11e8-8c72-1098e7feb32e.gif)

**Comment by EliverLara** [comment]
I tried to reproduce it in a vanilla ubuntu 18.04  installation but nothing happens :confused: .

![ubuntu](https://user-images.githubusercontent.com/9838260/43359692-2b614d24-926c-11e8-8091-11018a7c838c.gif)
