### ISSUE TITLE
The letters are erased. Theme icons do not appear

### ISSUE THREAD

**Issue by willian-fer** [EliverLara/Ant#56]
![captura de tela_2018-07-28_14-03-00](https://user-images.githubusercontent.com/33581079/43358878-2ef0e9c4-926f-11e8-97ac-3c1f48747ad4.png)

**Comment by EliverLara** [comment]
Hi, could you provide more info about your OS please?

**Comment by willian-fer** [comment]
Xubuntu 18.04

**Comment by EliverLara** [comment]
I suppose you're using Ant-Dracula because the other variants don't turn the titlebar black, so the problem is the window manager you're using, to solve it you can use the window manager of the theme itself.

**Comment by willian-fer** [comment]
It was really that, I did not think about switching, thanks for the answer.
