### ISSUE TITLE
Google Chrome buttons are too big

### ISSUE THREAD

**Issue by mister-magpie** [EliverLara/Ant#58]
In google chrome the buttons are bigger than they should be, this only happens with Ant Theme. Any way to fix it quickly? I'm Using Fedora 28 with all the latest updates.

**Comment by EliverLara** [comment]
HI, what buttons do you mean? the window controls?. If so, I'm also using fedora 28 with all the latest updates and everything looks good.

<details><summary>Screenshot</summary>
<p>

![captura de pantalla de 2018-09-04 12-29-52](https://user-images.githubusercontent.com/9838260/45047686-5e84f480-b03f-11e8-909f-1be44bc37585.png)

</p>
</details>

**Comment by mister-magpie** [comment]
Exactly, see the attached screenshot. The windows has regular size, google chrome are bigger.
![screenshot from 2018-09-04 19-51-08](https://user-images.githubusercontent.com/1387060/45048356-fa345600-b07b-11e8-9cdb-dd8880380c5a.png)

**Comment by mister-magpie** [comment]
solved by reinstalling google chrome using fedy.
