### ISSUE TITLE
How to adjust the top bar width?

### ISSUE THREAD

**Issue by ltoddy** [EliverLara/Ant#59]
thank your for your this beautiful theme.
but I think this top bar too wide.
![image](https://user-images.githubusercontent.com/20920763/45194724-d5f89500-b286-11e8-83d2-8aeeba391d87.png)

how to adjust this top bar, or where this css controlling code(I can modify source code by myself).

**Comment by EliverLara** [comment]
Hi, have you tried the slim version available in [Gnome-look](www.opendesktop.org/s/Gnome/p/1099856/)?

**Comment by ltoddy** [comment]
![image](https://user-images.githubusercontent.com/20920763/45195483-5b317900-b28a-11e8-8925-a76b6bf1d9b0.png)

I download this project release source code, and then move it to my `/usr/share/themes`.

**Comment by EliverLara** [comment]
Ok so you can download the slim version from gnome-look  or just checkout to the slim branch in the source that you have downloaded.

**Comment by ltoddy** [comment]
But I want to know where the control top bar `width` and `padding` css source code place.

**Comment by EliverLara** [comment]
Just check out "_header-bars.scss" that file contains the necessary for what you are looking for.

**Comment by ltoddy** [comment]
I modify the `min-width`, `padding-top`, `padding-bottom`, `margin-top`, `margin-bottom`, but there is not effect.

**Comment by ltoddy** [comment]
I download the `slim` version. I'm tired, I don't want to toss it.

**Comment by EliverLara** [comment]
You must modify the headerbar buttons properties too.
