### ISSUE TITLE
Grayed out task bar on elementary OS Juno (based on Ubuntu 18.04 LTS)

### ISSUE THREAD

**Issue by AfthabAhamed** [EliverLara/Ant#60]
Dear Developer,
I am a fan of the Ant themes and have been using it in elementary Os Loki without any trouble. Thank you for doing a wonderful job. However after switching to Juno (the latest release), I was trying out other themes and came across a peculiar bug unique to the Ant GTK theme(s) set and wish to bring this to your attention.

1. Greyed out task bar. 
2. Greyed out font.

I have attached a screen shot for further clarification.

Thank you,
Afthab

![screenshot from 2018-10-01 08 39 56](https://user-images.githubusercontent.com/32051189/46268525-9311a080-c558-11e8-8173-004bd396a183.png)

**Comment by EliverLara** [comment]
That's fixed!

**Comment by AfthabAhamed** [comment]
Dear developer,
Thank you for the fix and quick response. Keep up the good work. It is beautiful.
Also wanted to ask if you would consider maintaining a PPA for the themes you create.

Cheers and regards,
Afthab
