### ISSUE TITLE
System Profile Avatar Shape on Elementary Juno (Ubuntu 18.04)

### ISSUE THREAD

**Issue by AfthabAhamed** [EliverLara/Ant#62]
Dear Developer,
I came across another bug with regard to the Ant themes. The system profile Avatar is square isntead of circular. Please refer to the attachment. Hope you can fix this.
![elementary_default](https://user-images.githubusercontent.com/32051189/46577494-34d83800-ca06-11e8-8cc2-1bed62ca4e0c.png)
![ant](https://user-images.githubusercontent.com/32051189/46577497-373a9200-ca06-11e8-8437-76113a361835.png)
Regards,
Afthab

**Comment by EliverLara** [comment]
Thanks for reporting, I'll wok on that.
