### ISSUE TITLE
Changing pink color of Dracula on gtk-2.0?

### ISSUE THREAD

**Issue by EleosOS** [EliverLara/Ant#63]
Hi, I tried changing the pink color of Dracula like described in #27, but how do you do the same with gtk-2.0?
I had some success replacing all hex values in all files to the one I like, but some elements are still pink. Do you have to recolor the assets found in gtk-2.0/assets?

**Comment by EliverLara** [comment]
The simplest solution is to open  `gtk2.0/assets.svg` in a text editor and replace all the occurrences of the actual pink color for the one you like, then just run the `render-assets.sh` script and you're done.

**Comment by EleosOS** [comment]
Thanks!
