### ISSUE TITLE
Avatar not visible Elementary Juno (Ubuntu 18.04)

### ISSUE THREAD

**Issue by AfthabAhamed** [EliverLara/Ant#64]
Dear Developer,
Thank you for the bug fix to correct the avatar shape. However, Now the avatar is not visible. Please refer below attachment.
![screenshot from 2018-10-11 03-58-08](https://user-images.githubusercontent.com/32051189/46769884-d0b9ba80-cd0a-11e8-8a43-54d29c7cddb4.png)
Cheers,
Afthab

**Comment by EliverLara** [comment]
Thank you so much for reporting!, that's fixed in latest commit.
