### ISSUE TITLE
Colour mismatch on Ant Theme - Elementary OS Juno 

### ISSUE THREAD

**Issue by AfthabAhamed** [EliverLara/Ant#66]
Dear Developer,
The red highlight is missing on the power drop down panel.
![screenshot from 2018-11-15 07-48-06](https://user-images.githubusercontent.com/32051189/48526014-1fc7b200-e8ac-11e8-99b8-d9fdf6a9b3af.png)
![screenshot from 2018-11-15 07-47-34](https://user-images.githubusercontent.com/32051189/48526021-23f3cf80-e8ac-11e8-9fe0-00405e034f70.png)

Hope you will be able to provide a fix in time.

Thank you,
Afthab

**Comment by EliverLara** [comment]
Those are different widgets, that's why they are displayed in a different highlight color
