### ISSUE TITLE
How to change the font color white on the panel to other colors after maximizing?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [EliverLara/Ant#67]
![2018-11-25 19 02 33](https://user-images.githubusercontent.com/12076232/48978315-bbdf8d80-f0e4-11e8-95f9-af9983294204.png)

How can I change them?

ANT is a very beautiful theme, there are some minor problems under the primary operating system

**Comment by EliverLara** [comment]
Hi, what's your OS?

**Comment by Yakumo-Yukari** [comment]
@EliverLara  Sorry, I mean there are some minor problems with elementary os. I am using elementary os.

**Comment by Yakumo-Yukari** [comment]
@EliverLara In the app store, when the app is selected, the buttons and text will turn white
![2018-11-26 08 36 47](https://user-images.githubusercontent.com/12076232/48987104-d3eff500-f156-11e8-99d5-8ba2e407f523.png)

**Comment by EliverLara** [comment]
@Yakumo-Yukari thanks for the info, you can customize the top panel by editing the `gtk-3.20/apps/_pantheon.scss` file (under 'panel' section).

About the other issue, let me try to reproduce and fix it.

**Comment by Yakumo-Yukari** [comment]
@EliverLara Thank you～
