### ISSUE TITLE
How to force dark version of Ant 

### ISSUE THREAD

**Issue by ginwsby** [EliverLara/Ant#69]
Hi, I really like this theme! Just a question, is there a way to force the dark version of Ant? I like to use it both for the day and for the night. If I choose "dark mode" in app like Lollypop I see that the dark version works well. I know that Ant-Dracula exists, but I prefer Ant's color scheme.
Thanks in advance!

![schermata da 2018-12-02 10-31-27](https://user-images.githubusercontent.com/20545323/49338053-760f5180-f61d-11e8-84ee-e491ef6e44bc.png)

**Comment by EliverLara** [comment]
Hi, since the global-dark-theme option was removed from `tweaks`, you can manually: create (open if already present) the following file: 

`~/.config/gtk-3.0/settings.ini`

edit like this:

```bash
[Settings]
gtk-application-prefer-dark-theme=1
```

I hope that helps!

**Comment by ginwsby** [comment]
Wow! Seems working! Thanks a lot for the tip! :-)
