### ISSUE TITLE
Odd border on notification button

### ISSUE THREAD

**Issue by wout** [EliverLara/Ant#73]
Buttons in notifications seem to miss some styling. Borders are very heavy and don't match the overall style of the theme:

![image](https://user-images.githubusercontent.com/107324/52551460-ec2df280-2ddc-11e9-8030-040f68de1d1a.png)

**Comment by EliverLara** [comment]
Could you provide more info about your OS please?

**Comment by wout** [comment]
Yes, of course. I'm on Pop!_OS 18.10 (Ubuntu), using Ant for both applications and shell.
