### ISSUE TITLE
Emacs and gVim show fallback titlebar in dark theme

### ISSUE THREAD

**Issue by 0kaguya** [EliverLara/Ant#74]
I'm using the lastest version of Ant-Dracula theme, however the titlebar not show currectly in gVim and Emacs. They both have the default adwaita titlebars. It only happen in Ant-Dracula; no such problem in Ant. 
The gnome-shell version is 3.30.2.

**Comment by EliverLara** [comment]
Does this issue still persist? I've tested using gvim and it looks good
![captura de pantalla de 2019-02-27 13-49-05](https://user-images.githubusercontent.com/9838260/53518513-d5eb8c00-3a96-11e9-8262-8da4de9a40ac.png)

**Comment by 0kaguya** [comment]
yes it works fine now... no idea what happened.
