### ISSUE TITLE
Close buttons in overiew mode are oversized in GNOME 3.32

### ISSUE THREAD

**Issue by JuanCAlpizar** [EliverLara/Ant#75]
![image](https://user-images.githubusercontent.com/2028118/54971401-ea169200-4f4b-11e9-8abc-56d7028746ff.png)

As the name states, the close app buttons are twice as big as they used to be in the latest version of `gnome-shell`. There is also an ugly appearance when the close button is not focused, as shown in the image below:
![image](https://user-images.githubusercontent.com/2028118/54971393-dd923980-4f4b-11e9-8954-3e9540efd5bb.png)

**Comment by EliverLara** [comment]
Hola, ¿cual es tu versión de gnome?

**Comment by JuanCAlpizar** [comment]
@EliverLara 3.32.0, corriendo en Arch Linux con la última versión del repositorio estable

**Comment by p91paul** [comment]
I don't use this theme (found this thread on google), but the oversized button appears even without any theme enabled, don't know if it's the new gnome-shell default or what...

**Comment by EliverLara** [comment]
That's fixed with latest commits
