### ISSUE TITLE
window controls not displaying on Budgie

### ISSUE THREAD

**Issue by karjoseph** [EliverLara/Ant#77]
![missing](https://user-images.githubusercontent.com/40153194/61910847-bcdeee00-af03-11e9-9171-6ac8b5ef9155.png)

So I tried rotating through all the themes and it appears all of them are missing the window controls. Currently running Budgie on Manjaro and using Flat-Remix-Blue for my icons the regular window controls appear on the Nebula theme but the OSX window controls don't seem to be appearing.

**Comment by EliverLara** [comment]
Thank you so much for reporting! that's fixed now
