### ISSUE TITLE
Missing Radio Buttons and Checkboxes (Xubuntu)

### ISSUE THREAD

**Issue by getinmymailbox** [EliverLara/Ant#81]
Hi,

I've installed Ant-Dracula, Sweet-mars, and Sweet-Dark themes onto Xubuntu, and for the most part they look fantastic. 

I'm having a small issue with these, though. In the Appearance app itself, the radio buttons are missing. I'm not sure if this is a GTK3 + XFCE issue or something else. 

Here are screenshots from Ant-Dracula, Sweet-mars, and Sweet-Dark, respectively. 

![AntD](https://user-images.githubusercontent.com/60119693/72767868-8557b280-3bc3-11ea-8325-22cfc6dc787e.png)
![SweetMars](https://user-images.githubusercontent.com/60119693/72767865-8557b280-3bc3-11ea-8dac-f441ef99a37e.png)
![SweetDark2](https://user-images.githubusercontent.com/60119693/72767867-8557b280-3bc3-11ea-8323-ab9944f8abd3.png)

In Sweet-Dark you'll see that the radio buttons _are_ appearing in the Screenshot app but the checkboxes are not in the Appearance app. 

Well, I may have found the issue. I went poking around last night and found that the .png files for some of radio buttons and checkboxes are marked as symbolic links and also unreadable. I copied and renamed another set of radio buttons from the folder, and now they appear (though I assume they're not the ones you intended). I haven't had a chance to do the same to the checkboxes, so that's tonight's game plan. 

Do we know why these symbolic links don't work? Even in a new download where they just show as symbolic links but don't have the unreadable emblem, when I go to open one, it skips ahead to the next viewable image in the folder. (The same is true with Ant-Dracula, Sweet-Dark just happens to be the one I started with and is working best right now.)

![ NewDownloadVsThemeFolder](https://user-images.githubusercontent.com/60119693/72767923-c64fc700-3bc3-11ea-9540-71999c24401b.png)

I'll swap the other checkboxes in for the broken ones and can get by with that. Frankly the themes are too pretty to give up, regardless of if this is something fixable on the whole. 

Thanks for making these and suggesting I come over here to submit an issue!

Please let me know if I can provide any other screenshots or information.

**Comment by EliverLara** [comment]
Those symbolic links point to `base_theme_path/assets/` so, Could you make sure that folder is there? please.

**Comment by getinmymailbox** [comment]
Yes, the folder is there, but the images won't open. 

![Screenshot_2020-01-25_17-00-57](https://user-images.githubusercontent.com/60119693/73127830-58751800-3f94-11ea-9406-326ac78ffffb.png)

**Comment by EliverLara** [comment]
Could you try running [this](https://github.com/EliverLara/Ant/files/4129624/links.zip) file by extracting it under `theme_folder/gtk-2.0` and executing `sh links.sh`?
