### ISSUE TITLE
SolusOS Budgie launch bar doesn't auto-hide

### ISSUE THREAD

**Issue by shinskoll** [EliverLara/Ant#83]
Hi,
I installed your Ant20200317... The launch bar in SolusOS 4.1, whether on the sides or bottom doesn't auto-hide when set in "Automatic", the "intelligent" (or "smart", however it's called in English) works.
The default SolusOS theme actually make the bar hide whenever the mouse isn't on the edge.

EDIT : The default solus theme doesn't auto-hide the bar anymore either :/

EDIT2 : I'm not sure anymore, in my memory the automatic mode always hidden the bar and it just popped when the mouse was on the edge (now it's hidden only when a window is fullscreen), but the intelligent mode just kind of does that except it won't hide when no window is on the way.

Also, I use transparency and it look fine like that, but without transparency there's a weird white line on top, maybe it's just a matter of taste but i find it disgraceful (bug?) :
![Capture d’écran du 2020-03-29 08-41-38](https://user-images.githubusercontent.com/21128869/77843014-28671280-7199-11ea-9188-0b437710b2e7.png)

**Comment by shinskoll** [comment]
Sorry, my brain inverted the "intelligent" and "automatic" mode. Your theme is not at fault.

**Comment by shinskoll** [comment]
Actually... (!)
The taskbar won't popup when at exactly 53px height, right when the default icons will get bigger. At 54px it work again. So yeah, minor bug, and doesn't in a Solus live dvd in VirtualBox without Ant.

**Comment by EliverLara** [comment]
The white border issue is fixed, sadly I was unable to reproduce the other issue to provide a solution.

**Comment by shinskoll** [comment]
I think it's SolusOS related anyway, i've seen discussion about it on their tracker.
