### ISSUE TITLE
How do i set dark theme in gnome-tweaks ?

### ISSUE THREAD

**Issue by Jayanth-L** [EliverLara/Ant#91]
How do i set dark theme in gnome-tweaks ?
the Ant-dark is not shown in gnome-tweaks

so how can i achieve this ?

Thanking you in advance

Gnome version: latest
dist: arch linux

**Comment by EliverLara** [comment]
Hi, please take a look to #69

**Comment by Jayanth-L** [comment]
Yup! thank you.
