### ISSUE TITLE
Theme not applied to gnome-extesions app in Gnome40

### ISSUE THREAD

**Issue by xircon** [EliverLara/Ant#98]
This is a problem with every theme except Gnome's Adwaita-Dark:

![image](https://user-images.githubusercontent.com/1316691/116372965-d1e95f00-a804-11eb-8af8-cdf965b2b943.png)

Thanks!!

**Comment by EliverLara** [comment]
That's because `extensions` is a flaltpak application now.

**Comment by xircon** [comment]
Nope,  it is GTK4 thing.

**Comment by echevarriandre** [comment]
The WhiteSur theme is applied correctly for example. Mostly only your themes don't apply. Don't know if it's something related to how they are applied, but just wanted to point that out.
